export const AUTH_ERROR = "AUTH_ERROR";

export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const POST_USER_REQUEST = "POST_USER_REQUEST";
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const GET_USERS_REQUEST_ERROR = "GET_USERS_REQUEST_ERROR";
export const GET_USER_REQUEST_ERROR = "GET_USER_REQUEST_ERROR";
export const POST_USER_REQUEST_ERROR = "POST_USER_REQUEST_ERROR";
export const LOGIN_USER_REQUEST_ERROR = "LOGIN_USER_REQUEST_ERROR";
export const USER_LOADED = "USER_LOADED";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_LOADING = "USER_LOADING";


export const GET_ORDERS_REQUEST = "GET_ORDERS_REQUEST";
export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST";
export const POST_ORDER_REQUEST = "POST_ORDER_REQUEST";
export const PUT_ORDER_COMMISION_REQUEST = "PUT_ORDER_COMMISION_REQUEST";
export const PUT_ORDER_COMPLETE_REQUEST = "PUT_ORDER_COMPLETE_REQUEST";
export const GET_ORDERS_REQUEST_ERROR = "GET_ORDERS_REQUEST_ERROR";
export const GET_ORDER_REQUEST_ERROR = "GET_ORDER_REQUEST_ERROR";
export const POST_ORDER_REQUEST_ERROR = "POST_ORDER_REQUEST_ERROR";
export const PUT_ORDER_COMMISION_REQUEST_ERROR = "PUT_ORDER_COMMISION_REQUEST_ERROR";
export const PUT_ORDER_COMPLETE_REQUEST_ERROR = "PUT_ORDER_COMPLETE_REQUEST_ERROR";
export const ORDER_LOADING = "ORDER_LOADING";